name: scATAC

# one or more samples
samples:
  atac:
    read1: /scratch/AG_Ohler/Scott/sciATACtest/noSampleSheet/Undetermined_S0_R1_001.fastq.gz
    read2: /scratch/AG_Ohler/Scott/sciATACtest/noSampleSheet/Undetermined_S0_R2_001.fastq.gz

# Specify whether the reads should be trimmmed
trim_reads: True
# adapters to eliminate with flexbar
adapters: /data/ohler/Scott/Asli_Scripts/sciAtacAdapters.fa

# barcode reads and references contain the UMIs
barcodes:
  I1:
    reads: /scratch/AG_Ohler/Scott/sciATACtest/noSampleSheet/Undetermined_S0_I1_001.fastq.gz
    reference: /data/akalin/wkopp/sciatac_scott_data/reference_barcodes/I1.tab # can also be a fasta file containing the barcodes
  I2:
    reads: /scratch/AG_Ohler/Scott/sciATACtest/noSampleSheet/Undetermined_S0_I2_001.fastq.gz
    reference: /data/akalin/wkopp/sciatac_scott_data/reference_barcodes/I2.tab # can also be a fasta file containing the barcodes
  I3:
    reads: /scratch/AG_Ohler/Scott/sciATACtest/noSampleSheet/Undetermined_S0_I3_001.fastq.gz
    reference: /data/akalin/wkopp/sciatac_scott_data/reference_barcodes/I3.tab # can also be a fasta file containing the barcodes
  I4:
    reads: /scratch/AG_Ohler/Scott/sciATACtest/noSampleSheet/Undetermined_S0_I4_001.fastq.gz
    reference: /data/akalin/wkopp/sciatac_scott_data/reference_barcodes/I4.tab # can also be a fasta file containing the barcodes

# reference genomes to map against
# the paths should point to the respective bowtie2 indices
reference:
  dm6: 
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/dm6/dm6
    macs_gsize: dm
  danrer10: 
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/danrer10/danrer10
    macs_gsize: dm
    

# binsizes to bin the reference genome
binsize:
  - 1000
  - 2000
  - 5000
  - 10000

# flank to extend the macs2 peak summits at both sides
peak_flank:
  - 250
  - 500

# output directory
output_dir: /data/akalin/wkopp/sciatac_data/
