name: scATAC

samples: "./samplesheet.tsv"
barcodes:
    sheet: "./barcodesheet.tsv"
    correction: True
    min_mapq: 5
    max_mismatch: 2

# If the adapters are known, put them in a fasta file under the adapters field.
# flexbar will make use of them.
# On the other hand, if the adapters are not know, remove the adapters field.
# In this case, trim_galore will try to infer the adapter sequences.
adapters: /fast/AG_Akalin/wkopp/alison_sciatac_2018/adapters/sciAtacAdapters.fa

# reference genomes to map against
# the paths should point to the respective bowtie2 indices
min_mapq: 
 - 0
 - 10
#min_counts_per_barcode: 0
min_counts_per_barcode: 0
reference:
  danrer10:
    bowtie2index: /fast/AG_Akalin/wkopp/bowtie2_indices/danrer10/danrer10
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]
    annotation: 
      bulkatacpeaks: ../extra/danRer10_B_macs2.q0.01_peaks.bed
  danrer11:
    bowtie2index: /fast/AG_Ohler/Scott/danRer11/noAlt_danRer11
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]
  urchin:
    bowtie2index: /fast/AG_Akalin/wkopp/bowtie2_indices/Spurp3/Spurp3.1
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]

# Indictes that both ends of a paired-end alignment should be counted
# separatly. If True, both mates are counted at the 5' end. Otherwise,
# the midpoint between the two mates is counted once.
count_both_ends: True
compute_library_complexity: False

# binsizes to bin the reference genome
binsize:
  - 1000
  - 2000
  - 5000
  - 10000

# flank to extend the macs2 peak summits at both sides
peak_flank:
  - 250
  - 500

# output directory
output_dir: /data/akalin/wkopp/sciatac_data/

# this is the path to the java-based tool picard
picard_jarpath: /fast/AG_Akalin/wkopp/picard/build/libs/picard.jar
