name: scATAC

samples: "./samplesheet.tsv"
barcodes:
    sheet: "./barcodesheet.tsv"
    correction: True
    min_mapq: 5
    max_mismatch: 2

# If the adapters are known, put them in a fasta file under the adapters field.
# flexbar will make use of them.
# On the other hand, if the adapters are not know, remove the adapters field.
# In this case, trim_galore will try to infer the adapter sequences.
adapters: /data/ohler/Scott/sciATACtest/sciAtacAdapters.fa

# reference genomes to map against
# the paths should point to the respective bowtie2 indices
min_mapq: 
 - 0
 - 10
min_counts_per_barcode: 0
reference:
  dm6:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/dm6/dm6
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]
  danrer10:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/danrer10/danrer10
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]
    annotation: 
      bulkatacpeaks: ../extra/danRer10_B_macs2.q0.01_peaks.bed
      markergenes: ../extra/markergenes.bed
      markerpromoters: ../extra/markerpromoters.bed
      scrna_genebody: ../extra/scrna_genes.bed
      scrna_genepromoters: ../extra/scrna_study_promoters.bed
  urchin:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/Spurp3/Spurp3.1
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]

# Indictes that both ends of a paired-end alignment should be counted
# separatly. If True, both mates are counted at the 5' end. Otherwise,
# the midpoint between the two mates is counted once.
count_both_ends: False

# binsizes to bin the reference genome
binsize:
  - 200000
  - 10000
  - 1000
  - 2000
  - 5000

# flank to extend the macs2 peak summits at both sides
peak_flank:
  - 250

# output directory
output_dir: /scratch/AG_Akalin/wkopp/alison_sciatac_output/

# this is the path to the java-based tool picard
picard_jarpath: /data/akalin/wkopp/picard/build/libs/picard.jar
