name: scATAC

samples: "./samplesheet.tsv"
barcodes:
    sheet: "./barcodesheet.tsv"
    correction: True
    min_mapq: 5
    max_mismatch: 2

# Specify whether the reads should be trimmmed
trim_reads: trim_galore
# adapters to eliminate with flexbar
adapters: /data/ohler/Scott/Asli_Scripts/sciAtacAdapters.fa

# reference genomes to map against
# the paths should point to the respective bowtie2 indices
min_mapq: 0
min_counts_per_barcode: 0
reference:
  dm6:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/dm6/dm6
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]
  danrer10:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/danrer10/danrer10
    macs_gsize: dm
    removechroms: [chrM, _random, chrUn]


# binsizes to bin the reference genome
binsize:
  - 1000
  - 2000
  - 5000
  - 10000

# flank to extend the macs2 peak summits at both sides
peak_flank:
  - 250
  - 500

# output directory
output_dir: /data/akalin/wkopp/sciatac_data/
