name: scATAC

samples: "./samplesheet.tsv"
barcodes: "./barcodesheet.tsv"


# Specify whether the reads should be trimmmed
trim_reads: True
# adapters to eliminate with flexbar
adapters: /data/ohler/Scott/Asli_Scripts/sciAtacAdapters.fa

min_mapq: 5
max_mismatch: 2

# reference genomes to map against
# the paths should point to the respective bowtie2 indices
reference:
  dm6:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/dm6/dm6
    macs_gsize: dm
  danrer10:
    bowtie2index: /data/akalin/wkopp/bowtie2_indices/danrer10/danrer10
    macs_gsize: dm


# binsizes to bin the reference genome
binsize:
  - 1000
  - 2000
  - 5000
  - 10000

# flank to extend the macs2 peak summits at both sides
peak_flank:
  - 250
  - 500

# output directory
output_dir: /data/akalin/wkopp/sciatac_data/
