"""This script is supposed to generate the
pseudo genome for the barcodes.
"""
import itertools 
import argparse
from Bio import SeqIO  
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet.IUPAC import IUPACAmbiguousDNA

# sequences from scott's perl script
#Index read1;Tn5 barcode i7
references = {'I1': 'ATTACTCG TCCGGAGA CGCTCATT GAGATTCC ATTCAGAA GAATTCGT CTGAAGCT TAATGCGC CGGCTATG TCCGCGAA TCTCGCGC AGCGATAG',
#index Read 2; pcr barcode p7
'I2': 'TCGGATTCGG GCGGCTGCGG AGATTACGTT CTAACTAGGT CATAGCGACC CCGCTAAGAG ATGGAACGAA GCGTTCCGTT GGTTATCGAA GCATCGTATG AATACGATAA TTCCGTCGAC TCCGGCTTAT ACCAGGCGCA AGAGGAGAAT GTACTCCTAT GCTAACGGAT AGTTGAATCA TGATTAGGTA TCGTAGCATC TCTTGAGGTT AGGTCAGCTT TATTAGACTT CTCAATTAGT TCGCCGCCGG CCGTATGATT AACGCGCAGA CTCGTCGTAG CTAATTGCGA CGCGGCCATA AATATTACTT ATTGGCAGAT ATGGCGCCTG ATAAGGACTC TAGTAAGCCG ATTATGCAAG TTGGCAAGCC TTGATTGGCG GCATATGAGC GAACTCGACT CTAGCCAGCC TGCGACCTCT ATTCTTAGCT TTGATACGAT TATAATAGTT TTGCCGTAGG AGACCATATC TTGGTAAGGA CAGCTAGCGG CTAAGCCTTG CGTTACCGCT GACTGGACCA GCAAGACCGT TCAATCTCCT ATACCTCGAC TAGAGGCGTT TAGGTAACTT TTCGAATATT TGGACGACTA GTAGGCTGCA GTAGGATAAG CGTCGAGCGC ACTATTCATT TTGCTTAGAT CGAATGGAGC CTATATAGCC CTACTAATAA TGGTTGCCGT TCCTCTGCCG GATTCTTGAA GTAGCAGCTA CCTCAGCTCC AAGTAGCTCA TATTGCTGGA CCAGATACGG AACGAATTCG CGCTTATCGT AAGTACGCGA GATCTTCGCA TCTTAGCCTG TTATTGAGGC TTGCGAGCAT GCTTGAAGAG AGTCCGCTGC TAAGTCCTGA AGTTCTCATG CAGACTAAGG TCTATCGCTG GCGCTATGGT CATTATTATT AGCCGTAGTT TGATATTGCG ACGGCGTTAA GGCTTACTCC GCGCGTTCAT GAGCGCGATG',
#index read 3; Tn5 barcode i5
'I3': 'AGGCTATA GCCTCTAT AGGATAGG TCAGAGCC CTTCGCCT TAAGATTA ACGTCCTG GTCAGTAC',
#index read4;pcr barcode p5
'I4': 'CTCGATGGAG CGACTACCAA GTTGACGGCC CTCGTCTAGG GCTCTAACGA TGATAGAACG TTAGATTCCG GATCAGTCAT TCGATATTGA CCAGGTCTAC TTGGTCATAA AACGGACCAA TTAACGTACC GGACTCATTG GAACTGCATC GGAACGATGG ACTCTCTCAA GTCGCTCAGT TGATTCCTCA CCGTCGGAGG AGCGTCAATG CGAAGGACGA TTGAGTATCA TGAGGTAGAA GTTCCGACGA TCATCTCGAT GACTAGTCTA CTGCTTCGAC CCTAGCGCCT AGTTGCATCT TCGTAGGCTT AATTGCCTAC CGCCGCCTCC CAAGTACTGG CGGCGAGACC GACCTCCGCC TCTAGAACTA CTAACTCCAA ACCAAGATCT CGATCATTAC GACCTCTCTG GGCTAATTAA CGAGTTAGAG GATGATCGTA GCTCTCGCCT ACTATCTTGA AGGTCAATTA AAGCCGGCTG CTCCGGTTCT CATGCATCTC TCCGGTAATC ACCGTTACGA TCCGTCGCCA GGCTATGACT TGGACTTGAC ACTTCCGAAT AACTACCGAC CGTCCGTCCT GGTCCAGGAG AACGAGGCTA ACGTTCAACC ACGAGGACCT TATAACTTCC AGGATTACCA AACCTAGCTT AGTCCGCGGA ACTATCCGCA CGAGCTGCCA GACCGTAGCA GTCATTGCGC CAAGATTAAG ACGCAACTCC TGATACGAGT CATTATTACC TCTATAAGGA TTGGAGTCGG CAAGCTTGGC ATAGGATATG TGGCGTAGGT ACTGAATTCC TTCTACGCCA TGGCCGCAAT CCAAGCTGAA TGCCAGATGG AACTTATAAG TCATCTAATC AGATCCTATA CCTATAAGCT GATTGCAGAC ATAAGAGGCG AAGATCCAAC CTGCAATCGC GCAACTGGCA GATACCTAAG GGTAGGTCTC CTCGGTCAAT'}

def create_pseudo_genome(output_dir):

	for key in references:
		# split the strings
		inds = references[key].split(' ')

		record_list = []

		# loop over all combinations of indices and 
		# store them in a pseudo-ref. genome in fasta format
		for id_, ind in enumerate(inds): 
			record_list.append(SeqRecord(Seq(ind, IUPACAmbiguousDNA),
						     id='{}-{}'.format(key, id_))) 

			SeqIO.write(record_list, 
                                    output_dir + '/pseudo_genome_{}.fasta'.format(key), 
                                    "fasta")
